### ISSUE TITLE
**作業時間の見積もり**

### ISSUE THREAD

**Issue by PandaMic11** [Becom-Developer/yearconverter#1]
はじめての開発なので、丁寧に余裕を持ってい見積もりをする

**Comment by ykHakata** [comment]
**方向性として**
- 先に納期ありきで進めるやり方
- ~~作りたいものが明確で完成にかかる時間を見積もるやり方~~

**Comment by ykHakata** [comment]
稼働日数の定義
1day = 8h
１ヶ月の稼働の定義
平均30day、祝日のぞくと20day
7月末までとすると、最大で20day
今回は10dayの工数としておく
**決定: 10day = 80h**

**Comment by ykHakata** [comment]
最小の単位が0.5day = 4h
基本の単位が1day = 8h

1. 開発環境の準備(手順通りにやる): 0.5day
2. 画面のデザインと実装: 3day
3. 公開サーバーの準備(手順通りにやる): 0.5day 
4. ロジックの実装: 3day
5. 試作版のレビュー: 0.5day
6. 最終の修正: 1day
7. 完成版のレビュー: 0.5day
8. 予備日: 1day

**Comment by ykHakata** [comment]
こういうイメージで行きましょう
