### ISSUE TITLE
**開発環境の準備**

### ISSUE THREAD

**Issue by PandaMic11** [Becom-Developer/yearconverter#2]
手元のPCで開発する準備を行う
次回の開発のこともあるのでメモしておく

**Comment by ykHakata** [comment]
今回ここでは最低限のwebアプリの画面をつくるための準備をする
確認事項

テキストエディタ
サブライムテキストを活用する(準備済み)
参考
[https://github.com/ykHakata/PersonSearcher/wiki/EDITOR](https://github.com/ykHakata/PersonSearcher/wiki/EDITOR)

webブラウザ
google chrome を使う 表示->開発->デベロッパーツールで常に確認

ソースコードを github で管理する
アカウントのリボジトリ作成済み github 実践入門などを参考にする

支援ツール(css,js などのライブラリ活用)
[http://getbootstrap.com/](http://getbootstrap.com/
)
Bootstrap を活用してデザインを楽に作成する

**Comment by ykHakata** [comment]
yearconverter/doc/
このディレクトリに BootStrap からダウンロードしたものをおいていく
もし一つのファイルの容量が100メガ以上あるとgithubで管理できない
zip データをおいたらコミット
cd ~/github/yearconverter/
確認するコマンド
git status

git add .
git commit -m 'add doc'
git push

**Comment by ykHakata** [comment]
/doc/(ダウンロードしたものやメモをおく)
/html/ (画面のデザインの原案ファイルをおく)
