### ISSUE TITLE
**画面のデザインと実装**

### ISSUE THREAD

**Issue by PandaMic11** [Becom-Developer/yearconverter#3]
画面のデザイン注意点

デザインの良し悪しは人によって言う事がまちまちで終わりがないので、ある程度の妥協はしておく
画面の色合いやロゴ、画像などに着手するまえに最低限度必要な要素をテキストで書き出しておく

```
例:
西暦を入力する入力フォーム
和暦を入力する入力フォーム
変換実行ボタン
アプリの説明文
```

html, css, js これらはwebブラウザごとに挙動が違う場合がある
特にhtml は記述が間違ってもなんとなくうごく(表示される)
そういうこともあって、テキストエディタなどにソースコードの自動整形のライブラリあるので活用する

作業する時間は決めておかないとキリないことになる。

ファイル名を決めておく。
とりあえずわからないとき
index.html

サンプルの画面をつくりたいとき
sample.html

今回の例

最初にアクセスしたときに表示する画面

index.html
```
アプリのタイトル
アプリの説明文
西暦から和暦に変換するページへのリンクボタン
和暦から西暦に変換するページへのリンクボタン
```
wareki.html
```
アプリのタイトル
アプリの説明文
この機能の使い方の説明文
和暦から西暦に変換するページ
和暦の入力フォーム
実行ボタン
実行後に西暦を表示する部分(表示した状態)
メニューへ戻るボタン(リンク)
```

seireki.html
```
アプリのタイトル
アプリの説明文
この機能の使い方の説明文
西暦から和暦に変換するページ
西暦の入力フォーム
実行ボタン
実行後に和暦を表示する部分(表示した状態)
メニューへ戻るボタン(リンク)
```

result.html
```
アプリのタイトル
アプリの説明文
この機能の使い方の説明文
変換結果を表示する
メニューへ戻るボタン(リンク)
```

html のタグなどの参考ページ
[https://www.tagindex.com/
](https://www.tagindex.com/)
[http://getbootstrap.com/](http://getbootstrap.com/)
[https://www.colordic.org/](https://www.colordic.org/)
[https://lets-emoji.com/](https://lets-emoji.com/)

アプリ参考
[https://www.benricho.org/nenrei/sei-wa-conv.html](https://www.benricho.org/nenrei/sei-wa-conv.html)

html関連の
[https://www.w3.org/](https://www.w3.org/)

**Comment by ykHakata** [comment]
**2018/07/13 レビュー**

- 西暦の入力画面と和暦の入力画面は色を変える(つける)などして、違う画面だとわかりやすくする
- 暦の入力画面は入力フォームは一つだけにしてボタンやリンクは画面の下に集める
- 変換結果の画面をつくる(result.html)、内容は結果とトップへのリンク

**Comment by ykHakata** [comment]
こちら一旦クローズとする
