### ISSUE TITLE
html のヘッダー情報を正確に書いておく

### ISSUE THREAD

**Issue by ykHakata** [Becom-Developer/yearconverter#5]
https://github.com/Becom-Developer/yearconverter/blob/77f1c22d4141d4230fb6bbcde15912d2485d3c7b/html/index.html#L3

ヘッダー情報に utf8 の指定はしておいた方がよい、現在 google はwebサイトは基本 utf8 でないとうまく表示されなくても仕方がないかのような流れですすんでいるようなので、文字コードの指定がないと思わぬところでハマりポイントになってしまう。

参考
https://www.tagindex.com/html5/page/meta.html

**Comment by PandaMic11** [comment]
書いた！
