### ISSUE TITLE
html のみの記述の場合は絶対パスでなく相対パスで指定した方がいい

### ISSUE THREAD

**Issue by ykHakata** [Becom-Developer/yearconverter#6]
https://github.com/Becom-Developer/yearconverter/blob/77f1c22d4141d4230fb6bbcde15912d2485d3c7b/html/index.html#L19

このリンクのパスのやり方では、他のPCの場合はうまくリンクが繋がらない場合がある。
html のみの記述の場合リンクは相対パスで書くやり方が一般的

例

```html
<a href="seireki.html" class="btn btn-primary my-2">西暦を和暦に変換する</a>
```

**Comment by PandaMic11** [comment]
やった！
